# Generated by Django 5.2.6 on 2025-09-26 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=1000)),
                ('status', models.DateField(max_length=225)),
                ('created_date', models.DateField(max_length=255)),
                ('duration', models.IntegerField(max_length=255)),
                ('actions', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
    ]
