# Generated by Django 5.2.6 on 2025-09-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='title',
        ),
        migrations.AlterField(
            model_name='table',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='duration',
            field=models.IntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(max_length=225),
        ),
    ]
