# Generated by Django 5.2.6 on 2025-09-26 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list_app', '0002_remove_table_title_alter_table_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='duration',
        ),
    ]
