# Generated by Django 5.2.6 on 2025-09-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list_app', '0003_remove_table_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
